### ISSUE TITLE
Unable to release or serve from checkpoint

### ISSUE THREAD

**Issue by julsal** [OpenNMT/nmt-wizard-docker#156]
Hi, I've finished the training process using this wizard, which generated the following files in the `/root/models`

```
models
│   └── 0db23c95-8795-4bc8-82ab-1bf3e445c17b
│       ├── checkpoint
│       ├── checksum.md5
│       ├── ckpt-200000.data-00000-of-00002
│       ├── ckpt-200000.data-00001-of-00002
│       ├── ckpt-200000.index
│       ├── config.json
│       └── en-vocab-100k.txt
```
From this data, I tried to both `serve` and `release` the model using the following `config.json`.

```json
{
   "source":"en",
   "target":"el",
   "modelType": "checkpoint",
   "model": "0db23c95-8795-4bc8-82ab-1bf3e445c17b",
   "tokenization":{
      "source":{
         "vocabulary":"${CORPUS_DIR}/vocab/en-vocab-100k.txt"
      },
      "target":{
         "vocabulary":"${CORPUS_DIR}/vocab/it-vocab-100k.txt"
      }
   }
}
```
When running either `serve` or `release`, I get the same error.

```
2020-04-10 13:42:10Z.000648 [generic] WARNING get: /root/models/0db23c95-8795-4bc8-82ab-1bf3e445c17b does not exist on the remote
Traceback (most recent call last):
  File "entrypoint.py", line 217, in <module>
    OpenNMTTFFramework().run()
  File "/root/nmtwizard/utility.py", line 208, in run
    stats = self.exec_function(args)
  File "/root/nmtwizard/framework.py", line 278, in exec_function
    should_check_integrity)
  File "/root/nmtwizard/utility.py", line 291, in fetch_model
    check_integrity_fn=lambda m: check_model_dir(m, check_integrity_fn))
  File "/usr/local/lib/python3.5/dist-packages/systran_storages/storage.py", line 136, in get
    raise RuntimeError('Failed to synchronize %s' % local_path)
RuntimeError: Failed to synchronize /root/models/0db23c95-8795-4bc8-82ab-1bf3e445c17b
```
Could you what I'm doing wrongly?

**Comment by guillaumekln** [comment]
What command line are you running?

**Comment by julsal** [comment]
Dear @guillaumekln , thanks for the quick reply. In fact I was mounting the model's volume incorrectly. When I execute the command correctly, a get now a different error. 

This is the command:
`nvidia-docker run --rm -e NVIDIA_VISIBLE_DEVICES=1,2,3,4 -p 4000:4000 -v $PWD/models:/root/models -v $PWD/corpus:/root/corpus -v $PWD/release:/root/release nmtwizard/opennmt-tf -c /root/release/config_release.json -g 1,2,3,4 serve --host 0.0.0.0 --port 4000`

Which generates the following error:

```
2020-04-10 16:26:54Z.000076 [utility] INFO build_model_dir: Building model package in /root/workspace/output/0db23c95-8795-4bc8-82ab-1bf3e445c17b_release
Traceback (most recent call last):
  File "entrypoint.py", line 217, in <module>
    OpenNMTTFFramework().run()
  File "/root/nmtwizard/utility.py", line 208, in run
    stats = self.exec_function(args)
  File "/root/nmtwizard/framework.py", line 358, in exec_function
    config, model_path, args.host, args.port, gpuid=self._gpuid)
  File "/root/nmtwizard/framework.py", line 641, in serve_wrapper
    self._serving_state(local_config),
  File "/root/nmtwizard/framework.py", line 849, in _serving_state
    state['src_tokenizer'] = tokenizer.build_tokenizer(tok_config['source'])
  File "/root/nmtwizard/tokenizer.py", line 13, in build_tokenizer
    return pyonmttok.Tokenizer(**args)
TypeError: __init__(): incompatible constructor arguments. The following argument types are supported:
    1. pyonmttok.Tokenizer(mode: str, bpe_model_path: str = '', bpe_vocab_path: str = '', bpe_vocab_threshold: int = 50, vocabulary_path: str = '', vocabulary_threshold: int = 0, sp_model_path: str = '', sp_nbest_size: int = 0, sp_alpha: float = 0.1, joiner: str = '\uffed', joiner_annotate: bool = False, joiner_new: bool = False, spacer_annotate: bool = False, spacer_new: bool = False, case_feature: bool = False, case_markup: bool = False, soft_case_regions: bool = False, no_substitution: bool = False, preserve_placeholders: bool = False, preserve_segmented_tokens: bool = False, segment_case: bool = False, segment_numbers: bool = False, segment_alphabet_change: bool = False, support_prior_joiners: bool = False, segment_alphabet: list = [])

```

**Comment by guillaumekln** [comment]
You should configure the tokenization block for serving. See https://github.com/OpenNMT/nmt-wizard-docker/#tokenization

**Comment by julsal** [comment]
Models are now working. Thanks! However, For both models I trained, the results are:
```
curl -X POST http://localhost:4000/translate -d '{"src":[{"text": "Hello world!"}]}'
```

```
{"tgt": [[{"score": -359.366943359375, "text": "<unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk> <unk>"}]]}%                                                    
```
In another model is
```
{"tgt": [[{"text": "<unk>", "score": -11.183103561401367}]]}% 
```
Do you have an idea why I got this results? I'm training using the EuroParl dataset. I generated the vocabulary as below.

```
onmt-build-vocab --size 100000 --save_vocab en-vocab-100k.txt en.txt
```

**Comment by guillaumekln** [comment]
The tokenization configuration should match the one you used for training. Is that the case?

**Comment by julsal** [comment]
I'll double check, and eventually, restart the training process using a consistent tokenizer. Thanks for your help!
